### ISSUE TITLE
Panic on windows even with tls-disable flag

### ISSUE THREAD

**Issue by Scratch-net** [dedis/drand#151]
I might be mistaken but the tls-disable flag must be defined for the app for testWindows() function to succeed and it's not.
```go
app.Flags = toArray(verboseFlag, folderFlag)
```
But even if we fix this issue the code panics [here](https://github.com/dedis/drand/blob/0509cb73af6d4a7bc366d53687351a480f04adda/public.go#L49) because, well, **system root pool is not available on Windows**

But even if we get rid of the defaultManager and call core.NewGrpcClient() directly it still panics because of [this](https://github.com/dedis/drand/blob/f9d7514ab1709fb75b69f3c5320b4c77cc1e7465/net/client_grpc.go#L48)

So, there's no easy way to "disable TLS" on windows right now

**Comment by nikkolasg** [comment]
I'm sorry to announce you that but Windows is not officially supported and we clearly don't have the resources to make that happen in the near future.
You are welcome to provide pull requests if you do want to make that happen though :)

Closing for now (for obvious reasons).
