### ISSUE TITLE
Docker launch command incomplete?? It won't run from Kitematic

### ISSUE THREAD

**Issue by no-good-usernames-left** [dedis/drand#153]
I'm trying to get the Drand container to run so that I can set it up for random generation on the network.  But it won't run long enough to inject the launch command to set it up. 

The documented launch command feels incomplete and isn't enough detail for a docker newbie to get it off the ground. I get the idea of containers, but there's something missing and I don't know what it is to get it to work from a Kitematic viewpoint. 

Expected: 
Drand container start 
Console into it
Apply configuration (public/private/keygen/etc.) 
Activate config
Drand Generation started

**Comment by nikkolasg** [comment]
Could you explain a bit more what is your main goal here ? 
If you just want to run a few drand containers to get randomness, you can already run the script : `sudo run_local.sh`
If you want to setup drand in your local network on different machines USING docker, then you can follow the newest procedure for dockers: https://github.com/dedis/drand/blob/master/README_docker.md
Otherwise, simply rund drand natively and follow the instructions. If you dont understand one line, drop a question here.

**Comment by no-good-usernames-left** [comment]
Hi, 


Do you have a script for an automated setup of the entire thing? 
If it prompts for variables like hostname, cluster count, public/private, etc. I can work with that. 


I really am trying to learn docker, but only half of it makes sense like how keep persistent configuration data or building them from scratch. 


I can fetch containers, run them and then finalize setup, but if the container needs to be built/injected with stuff before launching, I'm lost. 





On June 19, 2019 at 7:36 AM, Nicolas Gailly <notifications@github.com> wrote:



Could you explain a bit more what is your main goal here ?
If you just want to run a few drand containers to get randomness, you can already run the script : sudo run_local.sh
If you want to setup drand in your local network on different machines USING docker, then you can follow the newest procedure for dockers: https://github.com/dedis/drand/blob/master/README_docker.md
Otherwise, simply rund drand natively and follow the instructions. If you dont understand one line, drop a question here.

**Comment by nikkolasg** [comment]
> Do you have a script for an automated setup of the entire thing? 

There isn't a *single* thingso short answer is no. But as mentionned previously, you can find a much more detailled document about how to use drand in Docker in production [here](https://github.com/dedis/drand/blob/master/README_docker.md). Feel free to ask questions if stg's not clear.

**Comment by lbarman** [comment]
There is a beta version of it here: https://github.com/dedis/drand/pull/158
You might try to check out the branch corresponding to this PR and follow `deploy-example/README_docker.md`.
This has not been peer-reviewed yet, you might want to wait for it to be merged in master. Or you can test it, feedbacks welcome :)
