### ISSUE TITLE
should only allow TLS versions 1.2 and higher

### ISSUE THREAD

**Issue by jeffallen** [dedis/drand#157]
I got this report from the IT people about drand.cothority.net:
```
'Vulnerable' cipher suites accepted by this service via the SSLv3 protocol:

TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (SWEET32)
TLS_RSA_WITH_3DES_EDE_CBC_SHA (SWEET32)

'Vulnerable' cipher suites accepted by this service via the TLSv1.0 protocol:

TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (SWEET32)
TLS_RSA_WITH_3DES_EDE_CBC_SHA (SWEET32)

'Vulnerable' cipher suites accepted by this service via the TLSv1.1 protocol:

TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (SWEET32)
TLS_RSA_WITH_3DES_EDE_CBC_SHA (SWEET32)

'Vulnerable' cipher suites accepted by this service via the TLSv1.2 protocol:

TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (SWEET32)
TLS_RSA_WITH_3DES_EDE_CBC_SHA (SWEET32)
```

I'm not sure I completely agree with them about what is vulnerable and not, but I do agree with them that drand is allowing TLS versions lower than 1.2, which doesn't make sense, because it is a new server and any reasonable client who is talking to it in 2019 will be able to talk TLS 1.2.

Cloudflare has an excellent blog post on this topic: https://blog.cloudflare.com/exposing-go-on-the-internet/

**Comment by nikkolasg** [comment]
Good point, I completely agree.

**Comment by jeffallen** [comment]
Any ETA on this? The IT department would like us to close this "hole".
