### ISSUE TITLE
reload the certificate file when it changes on disk

### ISSUE THREAD

**Issue by jeffallen** [dedis/drand#174]
My certificate was renewed by certbot correctly via a cron job. The certificate being used by the running drand instance is still the expired certificate, not the correct certificate on disk.

I could add a drand restart to the certbot post-renew hook, but it would be better if drand reloaded the certificate when it needed it.

**Comment by nikkolasg** [comment]
drand should be behind nginx anyway that will handle all this much better -> instructions will come to put nginx in front that should resolve the problem.

**Comment by PizzaWhisperer** [comment]
@nikkolasg @jeffallen now that #176 is merged, is this all good ?

**Comment by jeffallen** [comment]
I prefer the solution used in dedis/onet#576, but I understand your reasoning.
