### ISSUE TITLE
db folder should be set after config folder is set

### ISSUE THREAD

**Issue by mahrud** [dedis/drand#43]
Even when `--config` is set, because of this line the db folder is created in the default config folder.
https://github.com/dedis/drand/blob/e268dedc327f443a07f2e77a1831aff407971423/main.go#L49

**Comment by nikkolasg** [comment]
Cool, thanks, feel free to PR that change !

**Comment by mahrud** [comment]
I'll test a few more things and add more commits if I find anything else, then make one PR.

**Comment by PizzaWhisperer** [comment]
Fixed with #47
